import { useMemo, useState } from "react";
import "./styles.css";

type Lead = { id:string; name:string; company:string; email:string; owner:string; stage:string; lastContact:string; value:number };
const initial: Lead[] = [
  { id:"l1", name:"Maya Chen", company:"Northstar Home", email:"maya@northstar.example", owner:"Chris", stage:"Proposal", lastContact:"2026-08-07", value:8500 },
  { id:"l2", name:"M. Chen", company:"Northstar Home", email:"MAYA@northstar.example", owner:"Unassigned", stage:"New", lastContact:"2026-08-02", value:8500 },
  { id:"l3", name:"Andre Silva", company:"Fieldwork Co.", email:"andre@fieldwork.example", owner:"Chris", stage:"Discovery", lastContact:"2026-07-24", value:12000 },
  { id:"l4", name:"Priya Shah", company:"Kindred Studio", email:"priya@kindred.example", owner:"Chris", stage:"Qualified", lastContact:"2026-08-09", value:6200 },
  { id:"l5", name:"Jordan Lee", company:"Common Ground", email:"jordan@commonground.example", owner:"Unassigned", stage:"New", lastContact:"2026-07-18", value:4800 },
];
const daysSince=(date:string)=>Math.max(0,Math.floor((Date.parse("2026-08-10")-Date.parse(date))/86400000));
const urgency=(lead:Lead)=>Math.min(100,daysSince(lead.lastContact)*4+(lead.owner==="Unassigned"?25:0)+(lead.stage==="Proposal"?15:0));
const duplicateGroups=(leads:Lead[])=>{const map=new Map<string,Lead[]>(); leads.forEach(l=>{const key=l.email.toLowerCase();map.set(key,[...(map.get(key)||[]),l]);});return [...map.values()].filter(g=>g.length>1);};

export default function App(){
  const [leads,setLeads]=useState(initial); const [selectedId,setSelectedId]=useState(initial[0].id); const [query,setQuery]=useState("");
  const selected=leads.find(l=>l.id===selectedId) || leads[0]; const duplicates=duplicateGroups(leads);
  const visible=useMemo(()=>[...leads].filter(l=>`${l.name} ${l.company} ${l.email}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>urgency(b)-urgency(a)),[leads,query]);
  const unassigned=leads.filter(l=>l.owner==="Unassigned").length; const stale=leads.filter(l=>daysSince(l.lastContact)>=14).length;
  const patch=(id:string,next:Partial<Lead>)=>setLeads(rows=>rows.map(l=>l.id===id?{...l,...next}:l));
  const mergeDuplicates=()=>{const duplicateIds=new Set(duplicates.flatMap(group=>group.slice(1).map(l=>l.id)));setLeads(rows=>rows.filter(l=>!duplicateIds.has(l.id)));setSelectedId(initial[0].id);};
  const download=()=>{const header="name,company,email,owner,stage,last_contact,value\n";const body=leads.map(l=>[l.name,l.company,l.email.toLowerCase(),l.owner,l.stage,l.lastContact,l.value].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([header+body],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="clean-crm-pipeline.csv";a.click();URL.revokeObjectURL(url);};
  return <div className="app-shell"><header className="site-header"><a className="brand" href="https://foxandhenllc.com"><span className="brand-mark">F&amp;H</span><span><strong>Fox &amp; Hen</strong><small>Mini CRM Rescue</small></span></a><nav aria-label="Primary navigation"><a href="#queue">Queue</a><a href="#inspector">Inspector</a><a className="nav-button" href="https://github.com/foxandhenllc/foxhen-mini-crm-rescue">Repository</a></nav></header><main>
    <section className="hero"><div><p className="service-line">Local CRM cleanup</p><h1>Find duplicate leads and neglected follow-ups.</h1><p className="lede">Work through a fictional pipeline, merge exact-email duplicates, assign owners, and export a cleaner CSV. Everything stays in this browser session.</p><div className="hero-actions"><a className="primary-action" href="#queue">Review rescue queue</a><button className="secondary-action" onClick={download}>Export clean CSV</button></div></div><aside className="score-console"><div className="console-topline"><span>Pipeline scan</span><strong>{leads.length}</strong></div><div className="metric-grid"><article><span>Duplicates</span><strong>{duplicates.length}</strong><small>exact email matches</small></article><article><span>Unassigned</span><strong>{unassigned}</strong><small>owner gaps</small></article><article><span>Stale</span><strong>{stale}</strong><small>14+ days</small></article></div></aside></section>
    <section id="queue" className="board-layout"><div className="section-heading"><p>Rescue queue</p><h2>Highest-risk follow-ups first.</h2></div><div className="controls"><input aria-label="Search leads" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, company, or email"/><button onClick={mergeDuplicates} disabled={!duplicates.length}>Merge exact duplicates</button></div><div className="work-grid"><div className="item-list">{visible.map(l=><button key={l.id} className={selected.id===l.id?"item-card selected":"item-card"} onClick={()=>setSelectedId(l.id)}><span className={l.owner==="Unassigned"?"status blocked":"status active"}>{l.owner}</span><strong>{l.name}</strong><small>{l.company} · {l.stage} · ${l.value.toLocaleString()}</small><em>Urgency {urgency(l)}</em></button>)}</div><aside id="inspector" className="inspector"><div className="inspector-header"><span className="status ready">Lead record</span><strong>{daysSince(selected.lastContact)} days since contact</strong></div><h3>{selected.name}</h3><p className="inspector-note">{selected.email} · {selected.company}</p><label>Owner<select value={selected.owner} onChange={e=>patch(selected.id,{owner:e.target.value})}><option>Unassigned</option><option>Chris</option><option>Operations</option></select></label><label>Stage<select value={selected.stage} onChange={e=>patch(selected.id,{stage:e.target.value})}>{["New","Discovery","Qualified","Proposal","Won","Lost"].map(x=><option key={x}>{x}</option>)}</select></label><label>Last contact<input type="date" value={selected.lastContact} onChange={e=>patch(selected.id,{lastContact:e.target.value})}/></label><label>Estimated value<input type="number" value={selected.value} onChange={e=>patch(selected.id,{value:Number(e.target.value)})}/></label></aside></div></section>
  </main></div>;
}
